version: "3.7"
services:
  database:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: xbrl
    # Update the port if needed.
    ports:
      - 5432:5432
    volumes:
      - xbrl-database:/var/lib/postgresql/data

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6378:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
volumes:
  xbrl-database:
  cache: