<?php

return [
    "Director" => [
        "Director",
        "Director, 10% owner",
        "Director, See Remarks",
        "Director, See remarks, 10% owner",
        "Director, See remarks",
        "Director, See Remarks, 10% owner",
        "Director, 10% owner, Director-by-Deputization",
        "Director, Chief Digital Officer",
        "Director, 10% owner, See Remarks"
    ],
    "Chief Executive Officer (CEO)" => [
        "Director, Chief Executive Officer",
        "Director, President and CEO",
        "Director, President & CEO",
        "Director, Chairman and CEO",
        "Director, Co-CEO, Co-Founder, 10% owner",
        "Director, CEO, Director, 10% owner",
        "Director, CEO",
        "Director, Chief Executive Officer, 10% owner",
        "Director, President, CEO",
        "Director, COB and CEO, 10% owner",
        "Director, CEO, CFO, Secretary, 10% owner",
        "Director, Chairman & CEO",
        "Director, CEO and President",
        "Director, Chair and CEO",
        "Chief Executive Officer",
        "Director, CHIEF EXECUTIVE OFFICER",
        "Director, CEO & President",
        "Director, Chairman and CEO, 10% owner",
        "Director, Chairman, President & CEO",
        "Director, PRESIDENT AND CEO",
        "President and CEO",
        "President & CEO",
        "Director, CHAIRPERSON & CEO",
        "Director, Chairman, President and CEO",
        "Director, CEO, 10% owner",
        "Director, President and CEO, 10% owner",
        "Director, Chairman, CEO & President",
        "Director, PRESIDENT & CEO",
        "Director, CEO and Chairman",
        "Director, CEO AND PRESIDENT",
        "Co-CEO CCB",
        "Director, CHAIRMAN AND CEO",
        "Director, Pres. & Chief Exec. Officer",
        "Director, President & CEO, 10% owner",
        "CEO",
        "Director, Co-Chief Executive Officer",
        "CEO and President",
        "Director, Chairman & CEO, 10% owner",
        "Director, Co-CEO",
        "Director, CHAIRMAN & CEO",
        "Director, Chairman, CEO and President",
        "CEO Commercial Banking",
        "Director, CEO and Chairman, 10% owner",
        "Co-CEO",
        "Director, CHIEF EXECUTIVE OFFICER, 10% owner",
        "Director, CEO & Chair of the Board, 10% owner",
        "Director, CEO & PRESIDENT",
        "Director, Chairman and Co-CEO, 10% owner",
        "Director, Exec. Chairman & CEO",
        "Director, Chairman of the Board & CEO",
        "Director, Chairman, CEO",
        "Director, Chair & CEO",
        "Director, PRESIDENT, CEO and DIRECTOR",
        "Director, CEO and Director",
        "Director, Chairman of Bd., Pres. & CEO, 10% owner",
        "Director, PRESIDENT AND CEO, 10% owner",
        "Director, President, CEO and Chairman",
        "Director, President, CEO & Chairman",
        "Director, CEO, President and Director",
        "Director, CEO and President, 10% owner",
        "Director, Chair and Co-CEO",
        "Director, CEO & President, 10% owner",
        "Director, CEO & Chairman, 10% owner",
        "Director, CEO and Chairperson, 10% owner",
        "Director, President, CEO & Director",
        "Director, President/CEO",
        "CEO & President",
        "CHIEF EXECUTIVE OFFICER",
        "Director, Pres & Chief Executive Officer",
        "Director, Chairman and Co-CEO",
        "Director, Chair, President & CEO",
        "Director, Co-CEO and Director",
        "Director, Chairman of the Board and CEO",
        "President, CEO",
        "Director, CEO & President, Chairman of the Board",
        "Director, Executive Chairman and CEO",
        "Director, Board Chair and CEO",
        "Director, CEO and Chairman of the Board",
        "Director, Chair, President and CEO",
        "Director, CHAIRMAN, PRESIDENT & CEO",
        "Director, Co-Chief Executive Officer, 10% owner",
    ],
    "Chief Financial Officer (CFO)" => [
        "Chief Financial Officer",
        "CFO",
        "EVP & CFO",
        "EVP & Chief Financial Officer",
        "EVP and CFO",
        "CHIEF FINANCIAL OFFICER",
        "EVP, Chief Financial Officer",
        "EVP, CFO",
        "Executive Vice President & CFO",
        "Director, Chief Financial Officer",
        "SVP, Chief Financial Officer",
        "CFO and Treasurer",
        "SVP and CFO",
        "Executive VP and CFO",
        "SVP & Chief Financial Officer",
        "EVP, CFO & Treasurer",
        "CFO & Treasurer",
        "SVP & CFO",
        "President and CFO",
        "SVP, CFO",
        "Interim CFO",
        "Sr. EVP & CFO",
        "Sr. Exec VP and CFO",
        "EVP, CFO and Treasurer",
        "President & CFO",
        "EVP - Chief Financial Officer",
        "Senior Vice President and CFO",
        "SVP, CFO & Treasurer",
        "Senior Vice President, CFO",
        "EVP Chief Financial Officer",
        "EVP & CHIEF FINANCIAL OFFICER",
        "CFO and COO",
        "SVP, CHIEF FINANCIAL OFFICER",
        "Executive VP & CFO",
        "VP & CFO",
        "Sr. VP & CFO",
        "Sr. VP and CFO",
        "EVP/CFO",
        "EVP AND CFO",
        "VP & Chief Financial Officer",
        "Director, Ex. Vice President and CFO",
        "Senior VP and CFO",
        "Sr. Vice President & CFO",
        "SEVP, Chief Financial Officer",
        "VP and Chief Financial Officer",
        "Deputy Chief Financial Officer",
        "VP and CFO",
        "Vice President and CFO",
        "CFO and CIO",
        "CFO and Secretary",
        "Senior VP & CFO",
        "EVP, CFO AND TREASURER",
        "SVP & CHIEF FINANCIAL OFFICER",
        "EVP Finance CFO",
        "Director, CFO",
        "Vice President/CFO/Treasurer",
    ],
    "10% owner" => [
        "10% owner",
        "10% owner, Member of 10% owner group",
        "10% owner, Confidentiality agreement",
        "10% owner, See Remarks",
        "10% owner, See Footnote 2"
    ],
    "Executive Vice President" => [
        "Executive Vice President",
        "Senior Vice President",
        "Sr. Executive Vice President",
        "EVP",
        "Vice President",
        "Sr. Vice President",
        "EXECUTIVE VICE PRESIDENT",
        "SVP & CAO",
        "VICE PRESIDENT",
        "SVP",
        "EVP & CHRO",
        "SEVP",
        "SVP, Operations",
        "Vice President & Controller",
        "SENIOR VICE PRESIDENT",
        "Director, SENIOR VICE PRESIDENT",
        "EVP & CCO",
        "EVP, Global Operations",
        "EVP & CIO",
        "Executive VP, Banner Bank",
        "SVP, Corporate Controller",
        "SVP, CLO AND SECRETARY",
        "SVP, Worldwide Sales",
        "EVP - Operations",
        "Senior Exec. V.P.",
        "Director, Executive Vice President",
        "Exec VP",
        "EVP & Pres. External Affairs",
        "EVP, Global Human Resources",
        "EXEC. VP",
        "Executive VP",
        "SVP, Mktg & Strategy",
        "Sr Executive Vice President",
        "Executive Vice President, SCS"
    ],
    "Chief Operating Officer (COO)" => [
        "Chief Operating Officer",
        "President and COO",
        "President & COO",
        "Director, Chief Operating Officer",
        "CHIEF OPERATING OFFICER",
        "EVP & Chief Operating Officer",
        "EVP and COO",
        "EVP, Chief Operating Officer",
        "COO",
        "Director, President and COO",
        "EVP & COO",
        "Chief Operations Officer",
        "Chief Operations Executive",
        "SEVP & Chief Operating Officer",
        "EVP, COO",
        "Director, COO",
        "EVP, Chief Operations Officer",
        "EVP, Operations",
        "Executive Vice President & COO",
        "Co-Chief Operating Officer",
        "SVP, Chief Operating Officer",
        "CFO & COO",
        "COO, Gen Counsel and Secretary",
        "EVP & Chief Operations Officer",
        "EVP Chief Operating Officer",
        "Director, President & COO",
        "COO and CFO",
        "CO-COO AND EVP, 10% owner",
        "PRESIDENT & COO",
        "Co-COO and EVP, 10% owner"
    ],
    "Chief Accounting Officer" => [
        "Chief Accounting Officer",
        "Principal Accounting Officer",
        "SVP, Chief Accounting Officer",
        "VP, Chief Accounting Officer",
        "SVP & Chief Accounting Officer",
        "CHIEF ACCOUNTING OFFICER",
        "CAO/PFO",
        "VP & Chief Accounting Officer",
        "SVP-ChiefActngOfcr&Controller",
        "EVP & Chief Accounting Officer",
        "SVP - Chief Accounting Officer",
        "EVP, CAO & Controller",
        "CAO",
        "SVP, Controller & CAO",
        "EVP, Chief Accounting Officer",
        "PRINCIPAL ACCOUNTING OFFICER",
        "CVP, Chief Accounting Officer"
    ],
    "General Counsel" => [
        "General Counsel",
        "General Counsel and Secretary",
        "EVP and General Counsel",
        "EVP & General Counsel",
        "EVP, General Counsel",
        "SVP, General Counsel",
        "SVP and General Counsel",
        "General Counsel & Secretary",
        "EVP, Gen. Counsel & Secretary",
        "Global General Counsel",
        "SVP & General Counsel",
        "EVP, Gen Counsel & Secretary",
        "GENERAL COUNSEL",
        "Sr. Exec. VP and Gen. Counsel",
        "SVP, GC and Secretary",
        "EVP & GENERAL COUNSEL",
        "Sr. EVP and General Counsel",
        "General Counsel and CCO",
        "EVP, General Counsel & Sec.",
        "EVP, GC & Secretary",
        "EVP, GENERAL COUNSEL",
        "EVP, General Counsel & Sec",
        "SVP General Counsel",
        "VP and General Counsel",
        "EVP AND GENERAL COUNSEL",
        "EVP General Counsel",
        "SVP, GC & Secretary",
        "GC & Corporate Secretary",
        "SVP, General Counsel & Sec.",
        "SVP, Gen. Counsel & Secretary",
        "EVP, GC & Corporate Secretary",
        "GENERAL COUNSEL AND SECRETARY",
        "EVP, GC and Secretary",
        "EVP, Gen Counsel & Corp Sec",
        "VP, Gen. Counsel & Secretary",
        "VP General Counsel & Secretary",
        "EVP, Gen. Counsel & Corp.Sec.",
        "EVP - General Counsel",
        "VP & General Counsel",
        "SENIOR VP & GENERAL COUNSEL",
        "VP, General Counsel & Corp Sec"
    ],
    "See Remarks" => [
        "See Remarks",
        "See remarks",
        "SEE REMARKS",
        "See Remarks below.",
        "See remarks below.",
        "Please See Remarks",
        "*** See Remarks"
    ],
    "President" => [
        "President",
        "Director, President",
        "Pres, Merrill Wealth Mgmt",
        "President, International",
        "Group President",
        "Pres, Gl Corp & Invest Banking",
        "President, Global Markets",
        "Director, President, 10% owner",
        "President, The Private Bank",
        "PRESIDENT",
        "Co-President",
        "President & COO, CEO CIB",
        "President, Regional Banking",
        "Director, PRESIDENT",
        "EVP and President, Americas",
        "Director, Co-President",
        "Director, Co-President (See Remarks)",
        "EVP, Pres. - Bedding Products",
        "President, Field Operations",
        "Pres., Tim Hortons Americas",
        "Division President",
        "President, Americas"
    ],
    "Chairman" => [
        "Director, Executive Chairman, 10% owner",
        "Director, Executive Chairman",
        "Director, Chairman of the Board, 10% owner",
        "Director, Chairman of the Board",
        "Director, Executive Chair",
        "Director, Chairman",
        "Director, EXECUTIVE CHAIRMAN",
        "Director, Chairman, 10% owner",
        "Director, Exec. Chairman of the Board",
        "Executive Chairman",
        "Director, 10% owner, Chairman of the Board",
        "Director, Co-Chairman"
    ],
    "Chief Human Resources Officer" => [
        "Chief Human Resources Officer",
        "Chief People Officer",
        "EVP & Chief HR Officer",
        "EVP, Chief People Officer",
        "EVP, Chief HR Officer",
        "EVP, Human Resources",
        "VP, Human Resources",
        "Head of Human Resources",
        "EVP, CHRO",
        "SVP, Human Resources",
        "SVP, Chief People Officer",
        "EVP and CHRO",
        "SVP & Chief HR Officer",
        "EVP & Chief People Officer",
        "SVP and Chief People Officer",
        "SVP, Chief HR Officer",
        "CHIEF HUMAN RESOURCES OFFICER",
        "Sr. Exec VP-Human Resources",
        "SVP & CHRO",
        "CHIEF PEOPLE OFFICER",
        "EVP and Chief HR Officer",
        "SVP, CHRO",
        "Chief Human Resource Officer",
        "Chief HR Officer"
    ],
    "Chief Technology Officer (CTO)" => [
        "Chief Technology Officer",
        "Director, Chief Technology Officer",
        "EVP, Chief Technology Officer",
        "Chief Tech & Info Officer",
        "CTO and SVP Software Eng.",
        "EVP & Chief Technology Officer",
        "Director, Co-Founder and CTO",
        "Chief Technical Officer",
        "Pres/Chief Engineering Officer",
        "Director, Chief Technology Officer, 10% owner",
        "CHIEF TECHNOLOGY OFFICER",
        "Director, Chief Tech Officer, Co-Founder, 10% owner",
        "SVP, Chief Technology Officer",
        "CPO & CTO",
        "Director, CHIEF TECHNOLOGY OFFICER",
        "Director, EVP, Chief Technology Officer"
    ],
    "Chief Legal Officer" => [
        "Chief Legal Officer",
        "EVP, Chief Legal Officer",
        "CHIEF LEGAL OFFICER",
        "EVP & Chief Legal Officer",
        "EVP, CLO & Secretary",
        "EVP and Chief Legal Officer",
        "Chief Legal and HR Officer",
        "Chief Legal Officer & Sec.",
        "Chief Legal Officer, Secretary",
        "EVP, Chief Legal Officer & Sec",
        "Chief Legal Officer & Corp Sec",
        "SVP & Chief Legal Officer",
        "SVP, Chief Legal Officer"
    ],
    "Controller" => [
        "Controller",
        "Vice President and Controller",
        "Corporate Controller",
        "VP, Controller & CAO",
        "SVP and Controller",
        "Vice President, Controller",
        "SVP & Controller",
        "VP, Controller",
        "VP & Controller",
        "SVP, Controller and CAO",
        "Sr. VP & Co-Controller",
        "VP & Corporate Controller",
        "VP, Corporate Controller",
        "VP, Controller and CAO",
        "VP and Controller",
        "VP-Corporate Controller",
        "EVP and Controller"
    ],
    "Chief Commercial Officer" => [
        "Chief Commercial Officer",
        "EVP, Chief Commercial Officer",
        "EVP & Chief Commercial Officer",
        "CHIEF COMMERCIAL OFFICER",
        "SVP, Chief Commercial Officer",
        "SVP & Chief Commercial Officer",
        "Global Chief Comm. Officer"
    ],
    "Vice Chair" => [
        "Vice Chair",
        "Vice Chairman",
        "Vice Chair, Head Ent Credit",
        "Vice Chair, Gl Stra & Ent Plat",
        "Vice Chairman - Public Affairs",
        "Director, Vice Chairman"
    ],
    "Chief Marketing Officer" => [
        "Chief Marketing Officer",
        "Global Mktg Ofcr & SEVP Intl",
        "Chief Marketing & Growth Ofcr",
        "EVP, Chief Marketing Officer",
        "EVP & Chief Marketing Officer",
        "SVP, Chief Marketing Officer",
        "CHIEF MARKETING OFFICER",
    ],
    "Chief Medical Officer" => [
        "Chief Medical Officer",
        "CHIEF MEDICAL OFFICER",
        "EVP & Chief Medical Officer"
    ],
    "Executive Officer" => [
        "Chief Supply Chain Officer",
        "Square Lead",
        "Chief Innovation Officer",
        "Chief Platform Officer",
        "CEO Asset & Wealth Management",
        "Executive Officer",
        "SrEVP-Ext & Legal Affairs",
        "Managing Director",
        "Senior Managing Director",
        "Head of Aircraft OEM",
        "SVP and CAO",
        "CEO, COMMERCIAL BANKING",
        "Chief Banking Officer",
        "General Manager",
        "EVP & Chief Innovation Officer"
    ],
    "Chief Risk Officer" => [
        "Chief Risk Officer",
        "Sr. EVP and Chief Risk Officer",
        "EVP & Chief Risk Officer",
        "EVP and Chief Risk Officer",
        "EVP, Chief Risk Officer",
        "CHIEF RISK OFFICER",
        "EVP Chief Risk Officer"
    ],
    "Chief Administrative Officer" => [
        "Chief Administrative Officer",
        "Chief Legal/Admin Officer",
        "EVP & Chief Admin. Officer",
        "CHIEF ADMINISTRATIVE OFFICER",
        "EVP, Chief Admin Officer",
        "CFO and Chief Admin Officer"
    ],
    "Chief Revenue Officer" => [
        "Chief Revenue Officer",
        "Chief Sales Officer",
        "CHIEF REVENUE OFFICER",
        "SVP, Chief Revenue Officer"
    ],
    "Chief Information Officer" => [
        "Chief Information Officer",
        "EVP, Chief Information Officer",
        "SVP, Chief Information Officer",
        "EVP and CIO"
    ],
    "Chief Product Officer" => [
        "Chief Product Officer",
        "EVP, Chief Product Officer"
    ],
    "Chief Strategy Officer" => [
        "Chief Strategy Officer",
        "Chief Strategy & Dev Officer",
        "Director, Chief Strategy Officer, 10% owner",
        "EVP, Chief Strategy Officer",
        "EVP & Chief Strategy Officer",
        "Director, Chief Strategy Officer",
        "SVP, Chief Strategy Officer"
    ],
    "Member of a Group" => [
        "Member of a Group",
        "Member of a group",
        "Director, Member of a Group",
        "Member of 10% owner group"
    ],
    "Chief Scientific Officer" => [
        "Chief Scientific Officer",
        "CHIEF SCIENTIFIC OFFICER"
    ],
    "Chief Investment Officer" => [
        "Chief Investment Officer",
        "EVP, Chief Investment Officer",
        "EVP & Chief Investment Officer",
        "SVP & Co-Chief Invest. Ofcr."
    ],
    "Portfolio Manager" => [
        "Portfolio Manager"
    ],
    "Former 10% Owner" => [
        "Former 10% Owner"
    ],
    "Chief Development Officer" => [
        "Chief Development Officer",
        "EVP, Chief Development Officer"
    ],
    "Chief Credit Officer" => [
        "Chief Credit Officer",
        "EVP, Chief Credit Officer",
        "EVP & Chief Credit Officer",
        "EVP Chief Credit Officer"
    ],
    "Chief Business Officer" => [
        "Chief Business Officer",
        "SVP, Chief Business Officer"
    ],
    "Chief Corp. Dev. Officer" => [
        "Chief Corp. Dev. Officer",
        "EVP, CHIEF CORP DEV OFFICER"
    ],
    "Wife of CEO" => [
        "WIFE OF CEO"
    ],
    "Chief Growth Officer" => [
        "Chief Growth Officer",
        "SVP, Chief Growth Officer"
    ],
    "Chief Transformation Officer" => [
        "Chief Transformation Officer"
    ],
];