name: Vapor Deploy
concurrency: vapor
on:
  push:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        tools: composer:v2
        coverage: none
    - name: Add HTTP basic auth credentials
      run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json
    - name: Require Vapor CLI
      run: composer global require laravel/vapor-cli
    - name: Install Project Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader
    - name: Switch vappor team
      run: vapor team:switch --id 69977
    - name: Deploy to darkroom
      env:
        VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
      run: vapor deploy production
