name: Docker Deployment
on:
  push:
    branches:
      - development
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Setup AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Login to AWS ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 475344884420.dkr.ecr.us-east-1.amazonaws.com

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build and Push Docker image
      - name: Build and push Docker image
        run: |
          docker-compose -f docker-compose.production.yml build
          docker tag capitalyze:latest 475344884420.dkr.ecr.us-east-1.amazonaws.com/capitalyze-app:latest
          docker push 475344884420.dkr.ecr.us-east-1.amazonaws.com/capitalyze-app:latest

      # Notify completion
      - name: Notify Deployment Completion
        run: echo "Docker image has been successfully built and pushed to AWS ECR."
